# Change these first
owner: NetsBlox # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: NetsBlox
    url: https://netsblox.org
  - name: NetsBlox Editor
    url: https://editor.netsblox.org
  - name: NetsBlox Curriculum
    url: https://curriculum.netsblox.org
  - name: NetsBlox Login Portal
    url: https://login.netsblox.org
  - name: NetsBlox Documentation
    url: https://editor.netsblox.org/docs
  - name: RoboScape Online API
    url: https://roboscapeonlineapi2.netsblox.org/server/status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: NetsBlox Uptime
  introTitle: NetsBlox Uptime
  introMessage: Tracking outages in the NetsBlox ecosystem of tools and services!
  navbar:
    - title: Status
      href: /
    - title: NetsBlox
      href: https://netsblox.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
